[mysql]
db_username = 'goutham'
db_password = 'capstone12!'
db_host = 'capstone-mysql.mysql.database.azure.com'
db_port = '3306'
db_name = 'isb_demo'
#client_flags = '[mysql.connector.ClientFlag.SSL]'
client_flags = 65536
#ssl_ca = 'DigiCertGlobalRootG2.crt.pem'



